### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'isKeyObject')

### ISSUE THREAD

**Issue by mglikesbikes** [stytchauth/stytch-node#120]
When using `import * as stytch from 'stytch'` in a Remix.js project running on Cloudflare Workers, get the following error:

`TypeError: Cannot read properties of undefined (reading 'isKeyObject')`

Traces back to the following code in the `jose` package:

```
// node_modules/jose/dist/node/cjs/runtime/is_key_object.js
var require_is_key_object = __commonJS({
  "node_modules/jose/dist/node/cjs/runtime/is_key_object.js"(exports) {
    "use strict";
    init_react();
    Object.defineProperty(exports, "__esModule", { value: true });
    var crypto_1 = require_crypto2();
    var util = require_util();
    console.log(">>>>????", util.types);
    exports.default = util.types.isKeyObject
      ? (obj) => util.types.isKeyObject(obj)
      : (obj) => obj != null && obj instanceof crypto_1.KeyObject;
  },
});
```

See: https://github.com/panva/jose/issues/398

Any idea on your side?

**Comment by chris-stytch** [comment]
Heya @mglikesbikes !

Thanks for reporting this issue. Our Node client library leverages `axios` as a dependency and that library is incompatible with Cloudflare Workers; that means that today you cannot use `stytch-node` with Cloudflare Workers.

We're looking at migrating to `fetch` in the near future so that we can support Cloudflare Workers (amongst other niceties). We'll announce this change when it happens in our [Changelog](https://changelog.stytch.com/).

Until then I'm going to close this out in favor of the more specific issue here: https://github.com/stytchauth/stytch-node/issues/91

Thanks again @mglikesbikes , have a great day!
