### ISSUE TITLE
Cloudflare Worker Support: Consider using fetch instead of Axios

### ISSUE THREAD

**Issue by irvinebroque** [stytchauth/stytch-node#91]
👋 getting Stytch setup right now, with auth running on Cloudflare Workers.

This library *almost* works, but unfortunately it relies on Axios, which uses `XHR` instead of the cross-platform `fetch` API: https://github.com/axios/axios/issues/1219. If you run this in a worker, you'll get a `adapter is not a function` error. Looks like all that Axios is being used for is for some configuration and to intercept and throw specific errors. 

https://github.com/stytchauth/stytch-node/blob/6c3fc1ebb1c3e59340208804dd98b8cbaeea62e9/lib/client.ts#L55-L66

https://github.com/stytchauth/stytch-node/blob/6c3fc1ebb1c3e59340208804dd98b8cbaeea62e9/lib/shared.ts#L79-L98

Seems like dropping Axios would cut a dependency and simplify things, while allowing Stytch to be used in Workers/Deno/Vercel Edge functions. Would you be open to a PR?

**Comment by chris-stytch** [comment]
Heya Irvine!

In order to provide the widest range of compatibility for Node versions, we leverage Axios in `stytch-node` over `fetch`.

With that said, our team is evaluating moving to `fetch` in our next major version for all the reasons that you mention here, but our current major version of `stytch-node`, v3, will require Axios for now.

If you’d like to fork `stytch-node`, drop Axios and replace it with `fetch` we’d definitely encourage you to do so! Since our team is thinking about this for a future release, if you do end up forking it, please share it with us, we’d love to take a look and possibly incorporate it into a future release!

**Comment by Max-Stytch** [comment]
Hey @irvinebroque - we've rewritten the library to use `fetch` in our [v5.0.0 release](https://github.com/stytchauth/stytch-node/releases/tag/v5.0.0)

**Comment by jeremy-stytch** [comment]
Since [v5.0.0](https://github.com/stytchauth/stytch-node/releases/tag/v5.0.0) should work in Cloudflare Workers, I think we can close this issue. If you run into trouble using it, please open another issue!
